# Generated by Django 4.2.7 on 2026-04-30 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('normalized', models.TextField(db_index=True)),
                ('intent', models.CharField(max_length=50)),
                ('use_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-use_count', '-last_used_at'],
                'indexes': [models.Index(fields=['owner', 'normalized'], name='bookings_ch_owner_i_ddbee4_idx')],
            },
        ),
    ]
